const ClassificadoActionTypes = {
  FETCH_CLASSIFICADOS_START: "FETCH_CLASSIFICADOS_START",
  FETCH_CLASSIFICADOS_SUCCESS: "FETCH_CLASSIFICADOS_SUCCESS",
  FETCH_CLASSIFICADOS_FAILURE: "FETCH_CLASSIFICADOS_FAILURE",
  ADD_CLASSIFICADO_START: "ADD_CLASSIFICADO_START",
  ADD_CLASSIFICADO_SUCCESS: "ADD_CLASSIFICADO_SUCCESS",
  ADD_CLASSIFICADO_FAILURE: "ADD_CLASSIFICADO_FAILURE",
};

export default ClassificadoActionTypes;
